# Research question answering functionality

This app demonstrated what happens in the different callbacks of `app/callbacks/rq_callbacks.py`.

In [1]:
%load_ext autoreload
%autoreload 2

This first chunk of code downloads data and saves it to a local directory called `mock_session_data/`.

In the first tab of the app, data gets uploaded and depending on the format, two outputs are saved:

* `raw_text_files.jsonl` if the input data was text (e.g. `.txt` or `.vtt`)
* `topic_modelling_data.csv`: this is data that has been converted to a tabular format for topic modelling, if it was not originally in a table.

Basically this first chunk mocks what would happen if you'd already gone through the upload step in the app.

In [ ]:
from discovery_qualfml import PROJECT_DIR
from discovery_qualfml.utils.llm_summarize import generate_summaries_and_quotes, create_final_output_df, create_output_excel
from discovery_qualfml.utils.llm_question_answering import format_transcripts, run_batch_check_for_all_rqs, create_batch_check_outputs_all_rqs

import boto3
import os

def download_s3_folder(bucket_name, s3_prefix, local_dir, aws_profile=None, region_name='eu-west-2'):
    """
    Downloads an S3 folder to a local directory.

    Args:
        bucket_name (str): Name of the S3 bucket.
        s3_prefix (str): Prefix of the "folder" in S3 to download.
        local_dir (str): Local path to save the downloaded files.
        aws_profile (str, optional): Named AWS CLI profile to use.
        region_name (str): AWS region.
    """
    if aws_profile:
        session = boto3.Session(profile_name=aws_profile, region_name=region_name)
    else:
        session = boto3.Session(region_name=region_name)

    s3 = session.resource('s3')
    bucket = s3.Bucket(bucket_name)

    for obj in bucket.objects.filter(Prefix=s3_prefix):
        rel_path = obj.key[len(s3_prefix):].lstrip('/')
        local_path = os.path.join(local_dir, rel_path)

        if obj.key.endswith('/'):  # Skip directories
            continue

        os.makedirs(os.path.dirname(local_path), exist_ok=True)
        print(f'Downloading {obj.key} to {local_path}')
        bucket.download_file(obj.key, local_path)

# Example usage:
download_s3_folder(
    bucket_name='dsp-qualfml',
    s3_prefix='example_data/vtt_digestive/mock_session_data/',  # e.g., 'my-data/' (must end with / if it's a "folder")
    local_dir=f'{PROJECT_DIR}/outputs/mock_session_data/',
    aws_profile='default'  # Or None if using default credentials
)

/Users/rosie.oxbury/Documents/git_repos/discovery_qualfml/discovery_qualfml/utils/llm_summarize.py:20: LangChainDeprecationWarning: The class `AzureChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-openai package and should be used instead. To use it run `pip install -U :class:`~langchain-openai` and import as `from :class:`~langchain_openai import AzureChatOpenAI``.
  llm = AzureChatOpenAI(

2025-06-18 15:41:51,247 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
Downloading example_data/vtt_digestive/mock_session_data/raw_text_files.jsonl to /Users/rosie.oxbury/Documents/git_repos/discovery_qualfml/outputs/mock_session_data/raw_text_files.jsonl
Downloading example_data/vtt_digestive/mock_session_data/topic_modelling_data.csv to /Users/rosie.oxbury/Documents/git_repos/discovery_qualfml/outputs/mock_session_data/topic_modelling_data.csv

The callbacks in the file `rq_callbacks.py` need to know the session id, so this is provided below as `"mock_session_data"`.

The first input in that tab is for research questions, which are inputted as a string with each RQ on a new line. We mock that input with the variable `rq_text` below.

In [3]:
session_id = "mock_session_data"

rq_text = """
How do participants feel about their diagnoses?
What are some difficulties participants have faced because of their conditions?
"""

The callbacks in `rq_callbacks.py` are as follows:
* `run_analysis()` does a bunch of things:
    - reformats the session data into the shape needed for the different LLM prompting steps
    - runs the different LLM prompting steps i.e. getting an answer to the RQ for each interview, creating a summary answer across all interviews, pulling out the best quotes from the interviews
    - formats the output into an excel that contains the summary answer to each RQ, the key quotes and the conversation/file identifiers for those quotes
* `download_excel()` makes the excel output available for download when a button is clicked
* `display_results()` displays the summary answers and key quotes
* `display_conversation()` brings up a popup with the full conversation for a given quote when clicked

The rest of this notebook focuses mainly on what's going on in the `run_analysis()` callback as that's where most of the heavy lifting happens.

The key input format for this tab is a Dict where the keys are conversation/file IDs, and the values are the full text of each interview/file, as you can see below:

In [4]:
conversation_text_dict = format_transcripts(session_id, 'source_file', text_col='transcript')
conversation_text_dict

text files

{'barbara.vtt': 'WEBVTT\nB: Bowel disorders, it is what it is.\nI: How old were you when you first started to realize you were having problems with your digestion?\nB: I was, uh, 21 and a half, to be exact, yeah.\nI: And do you suffer from celiac or, how would you define your discomfort?\nB: My colonoscopy says no celiac and not inflammatory bowel disease. My blood marker test says I have inflammatory bowel disease. I would label myself definitely gluten intolerant.\nI: And for the record, can you describe what that means? Gluten intolerance? As you would describe it.\nB: Gluten intolerance means that you, your body just does not digest or break down or really absorb gluten. And that is a protein that is found in wheat. I would also say that I don’t handle processed wheat well either. Um, and the symptoms are across the board. For me personally, um, I get, I’ll get joint pains, exhaustion, um, and I just feel incredibly full. After four or five bites, if I’m having, say, pasta or something where it’s just, after four or five bites, I can’t eat anymore, feel nauseous. That’s actually where the symptoms really first started.\nI: Was there anything else beyond that?\xa0 Say migraine headaches or …\nB: Headaches. I have, and it’s gotten a lot better, I had, um, pretty bad hormonal acne, is what they would call it. Went across the board trying to treat it. I tried creams and antibiotics, retin-As, all that stuff. When I started to cut out gluten and wheats, my skin cleared up the best it’s ever been. I even went on Accutane and, I was on Accutane for five months and that is exactly when my symptoms would appear. I’ve been completely healthy my entire life.\nI: Do you think there is a connection between …\nB: Yes. I, well, studies have shown that if you possibly have Crohn’s disease or ulcerative colitis and you go on Accutane, there is research coming out that, it can set those diseases off. Um, and I just, I can’t, I think that’s what happened to me because of, like I said, I was completely healthy and then one day I’m having bowel issues and medications.\nI: You said you’ve seen doctors, medical doctors, what was that process like of getting tested? What was the response?\nB: Well, I went to, when I first got sick, I went to my internal medicine doctor and he’s like, “I don’t know if it’s acid reflux or what, so I’m gonna do a blood test on you.” And he did a blood panel, that’s when he said, “OK, according to these markers you have IBD, go to a gastrologist.”\xa0 And, I went to one that was recommended, um, and she was just like, “OK, I wanna scope you.”\xa0 I told her about all these symptoms and when I told her I’d been on Accutane, she kind of made a look like, “Oh, OK.” And then I have a family history, unfortunately, with inflammatory bowel disease. Both of my younger sisters have ulcerative colitis. I have an uncle who is deceased who had ulcerative colitis, and two or three second cousins that have ulcerative colitis and Crohn’s.\nI: Can you describe what ulcerative colitis is, as you would describe it?\nB: Um, it’s just your intestines not really absorbing the proper nutrients and inflammation, um, and that can be where, um, in any part of your gut. All the way to, Crohn’s can even burn your esophagus and mouth, all the way down through the rest of your body. It’s pretty intense. I was the healthy one. I didn’t have asthma or, not like my little sisters. The hell they went through in middle school with getting sick, I never had that.\nI: Would you be willing to talk a little more about that?\nB:\xa0 So, my first sister got sick right around middle school. Her symptoms were, any time she’d eat, she immediately would have to go to the bathroom, instant diarrhea. She’d break out in a sweat. She’d get [unable to transcribe], which is a kind of skin lesion, which is, we talked to the dermatologist and, but until you treat really the underlying problem, you don’t know what’s going on. Um, what else did she have? And just going from doctor to doctor. Um, they did a scope and there was a little inflammation that they did find. Um, but they still were very hesitant of saying, “Yes, you have ulcerative colitis” because she wasn’t on, your typical textbook case. I found that really hard for doctors. If it’s not black and white, they …\nI: We’ve discussed in other interviews, before this, the fear of using labels in …\nB: They’re terrified. I mean, I went through several doctors and then finally, um, I think kinda, and going through puberty, I and, while my sisters were going through puberty, it was really hard. With all the hormones and changing, It just kinda, I think, throws a lot of things off. And then my sister, she’s what would you call remission, but it’s never really going away. You’ll always still have it, but she been in remission for a while now. Um, found the right doctor and he didn’t label her until he started treating her.\nI: So it was sort of a trial by fire?\nB: Yeah, we’d kind of tell them, “Hey, can we try this? It’s not getting better.” And then my youngest sister, right around the same time, about sixth grade, she got sick as well. Different symptoms. Um, she didn’t have, she had ulcerative colitis. But, there can come blood when you go to the bathroom. And she went in, was severely sick, she went to the hospital. And filled up the little cup they have, completely, with blood. And when they went in to scope, they couldn’t find anything. But she had the blood. She had the joint ache. She has the rash. She’s trying to eat as much as she could, but her belly would distend. And they wanted to send my sister to the psych unit. They thought it was a mental thing and we’re like, “No, she’s filling up the cup.” Like, really? And it was just their reaction because they couldn’t figure out why because the gold standard in diagnosing these things is the colonoscopy. But it’s so hard with these diseases to find it.\nI: Why do you think there seems to be a reluctance or a unwillingness in wanting to just get right to the point?\nB: I’m not really sure. I don’t, I don’t know. I don’t know if they’re taught that in med school that, you know, that it’s not black and white. And we have found also that, when you are in a hospital setting, you don’t see the same doctor. You have a doctor for a week and then, you know, in all honesty, they weren’t all on the same page. They had their own egos and their own agendas. My sister was in there 21 days. Still, we were finally like, “This is enough. It’s not a psych problem, discharge her now.” And she was still bleeding, two weeks later, she was anemic. We ended up, by chance, being able to get into a different doctor at a different practice who would treat her as if. She was in remission for about three years, she’s out of it now, but she’s got good doctors. She’s still trying to figure out how to beat this beast.\nI: Are both your sisters, and you as well, on prescription medication?\nB: Um, yes. My little sister Tammy now, I think because she’s been in remission is on like a, something for acid reflux. My younger sister, she’s not on any medication. And my one sister, yes, but I don’t remember what she’s on.\nI: And, none of these symptoms have been shown in your parents?\nB: My mom, yeah. I remember growing up and her having bowel issues, yeah. And, it’s all on my mom’s side. My dad’s side doesn’t have any bowel issues. This gluten intolerance thing, I didn’t really understand it until I was taking a class with a friend and I was just telling her, “God, I really don’t like.” They labeled me as having GERD and put me on severe, pretty intense medication. I just don’t like the fact I have to take this medication.\nI: What is GERD?\nB: It’s similar to the acid reflux disease. So, a lot of it is by diet. Little things can set it off.\nI: Before all this, what was your favorite food?\nB: I loved pizza and burgers.\nI: Would you say you ate a pretty balanced diet? Not loading up on pasta …\nB: No, but it’s funny ‘cause when I was sick, that’s all I wanted, you know? That sounded really good to eat bread and crackers.\nI: Is that because it was a comfort basis?\nB:\xa0 No, um, I think people with that, like sugars and complex stuff, especially like all the sugar that’s really not good for you, it’s addicting, you know?\xa0 The longer you are away from it, it’s easier to stay away. Have a little and it’s like I gotta have more. It’s difficult.\nI: When you started to cut out gluten and bad sugars, what was the response?\nB: From like a friend?\nI: Yeah. Were you a partier?\nB: No. I was so, no, it was weird. I kinda went through my drinking when I was underage. By the time I turned 21, I really didn’t enjoy it. Actually, last night, I feel it. Like, I didn’t drink that much and I feel like hell the next day. Two beers. But, say if I have food and water with it, it’s still mm-mm. So, when I cheat, I’m like, “You’re gonna pay for it the next day.” But it’s hard. Not wanting to go out with friends and, you know, it gets kinda, after a while, “Oh, I’ll just have salad cause that’s really all I can eat.” I can still eat stuff, but finding restaurants that are accommodating to eating to that.\nI: Is there a feeling of being ostracized? Your friends or actually from the restaurant itself?\nB: Yeah, it’s complicated. I just tell them now.\nI: Do you have a specific experience that jumps out in your mind?\nB: Yeah, I’d just gotten, a couple of times when you ask, “Do you have a gluten-free menu?” They’re getting much better at it, but I remember when I first started, like a year and a half ago, it was still kind of like [rolls eyes], “Oh, you’re one of\xa0those\xa0people.” Um, cause some people will cut out gluten because they think it will be great for them. But it really doesn’t hurt them. So, I don’t like to be grouped into that. It’d be cheaper. Probably be easier just to be able to go with the flow.\nI: How does that make you feel when you talk to someone who says they’re cutting out gluten for my diet, but they can eat bread if they desperately wanted to?\nB: Um, close friends, no. Not at all. I mean, because, well, they’ve seen me not do well. I’m just not very nice either because I don’t feel well. Um, but strangers, yeah, that don’t get it. You know, there’s kind of a judgment and they, “Why are you, are you doing it to lose weight or … ?” No, I’m doing it ’cause I feel miserable. But that’s also something that’s going around like in the media, I know, it’s being hyped up as, “Cut out gluten, it’ll make you lose weight.” I think that anything, if you’re just trying, doing it to lose weight, that won’t stick.\nI: How do feel with all the mass market of gluten-free this, gluten-free that?\nB: It’s a little overwhelming, to be honest. You really have to look at the food labels. Are they taking out this? I still, and trying to find stuff, um, at the grocery store that I can eat, but it takes forever. I try to, at least, read every label. Grocery experiences are long [laughs].\nI: Is there a specific thing that you want, but know you can’t have?\nB: Yeah, that’s my downfall. I mean, I’ve found some places that are gluten-free. But, you know, I haven’t found, has anyone found a gluten-free pizza that you can make at home, send it my way ’cause [laughs] …\nI: In addition to reading labels and breakdown what I can and can’t eat in the moment, how has your lifestyle changed to feel comfort?\nB: With gluten intolerance, I’ve done some research. But I’ve gotten to the point where I’ve, I’m taking a class with a friend and she’s like, “I have stomach issues. Why don’t you read this book? It’s called\xa0Eat Right for Your Blood Type.” I didn’t know my blood type at the time, so I started reading the type-O diet and I was like, “Oh my god.” It describes how, based on if you eat these foods, it’s what you have. It’s so me. I had to kinda look away. Is this really me? And it was. So for me, I follow the hunter-gatherer type, meat, fruits, and vegetables. Um, and so that alone, that book and I’m so grateful for my friend, because that brought a sense of comfort.\nI: It sounds like you’ve got a lot of support around you.\nB: Yeah.\nI: And, have you been able to pass that along to your sisters? Did they ever talk to you about what it’s like to be in middle school and have, really feel, have these differences?\nB:\xa0 Oh yeah, it was really, really tough. Kids, not so much kids, but I remember the teachers would not, being, not really getting it. And my mom would try so hard to, I mean, “Hey, this is what my daughters have. There are the type of medications, heavy medication at one point that they were on. Heavy steroids that make you, not really there. Um, she’s maybe not paying attention because her pain or she’s trying not to shit her pants.” And, um, yeah they had a really hard time finding kids that understood what they were going through. And, it’s a disease on the inside that doesn’t always manifest on the outside. And I think a lot of diseases are like that. Just being aware.\nI: Especially when a lot of the symptoms are connected to other diseases? Are you concerned, have you thought about at all what this could lead to?\nB: That’s why I changed my diet because I know the blood markers, so, in some ways that kind of means I’m a ticking time bomb. You know, I could get the flu really, really bad. And that could set off this disease. Um, but I’m doing everything that I can in my power as far as diet that I can to control it. Because that also can set it off. I’ve adapted this new lifestyle. Exercise like three, four times a week. Um, that’s been the hardest one, to really stay committed. I’ve conquered the food part, but not putting in the exercise as well. And doing yoga ’cause I stress easily. And, that’ll feed into it, that stress will lead me into making poor food choices. So, finding the balance is what I’m really focusing on.\nI: Do you feel that, when you’ve had a bad day, it’s the emotional connection, or that emotion is tied to reactions? “I feel bad, I need comfort.”\nB:\xa0 That’s something to be aware of, definitely. That’s happened to me.\nI: Do you think there’s a danger in people becoming so emotion-oriented?\nB: Oh yeah. Um, yeah you gotta find balance you know? And being aware, it’s all kind of connected.\nI: Is there a point where you’ve had to battle and fears or overwhelming emotions? And you had to bring yourself back? Trigger or phrases that help keep you in balance?\nB: Um, I have to stay in the present. And not, “God, what if this happens?” ’Cause that, you know, will set it off. And that’s where I need to be, in that present and just focus on that. And when I don’t, that’s when it gets me and stresses me out. And in listening to your body is the best thing. You are your best advocate for yourself. Not taking the medical. Being in tune. It’s clear if I’ve had a bad week. I eat foods I shouldn’t have been eating. I feel really lethargic and exhausted. If you don’t want to feel like this, don’t eat it. It’s pretty immediate.\nI: Do you feel you’re leaning towards organic?\nB: I have found, for me, the hunter-gatherer, animal protein. I’d watch documentaries on how animals are being treated, on what they’re given and what we’re absorbing and the cancer rate and all. So, I tried vegetarian, but that means I upped my soy. A lot of soy, had a lot of grains too, even lentils, which are supposed to be really good. And I felt miserable. And I gained a lot of weight. And, they, “You know, don’t eat meat and you’ll lose weight.” For me, I felt horrible. Like, my skin was breaking out, I gained weight. I think like everyone is honestly a little bit different. It’s unfair to the consumer. I gotta eat animal protein or I’m not a very nice woman. I’m cranky. Watch out! But, on the other side, I’ve got to pay more for grass-fed animal meat that’s not injected with hormones. I think that’s what’s causing the cancer and all these problems. It’s because of what they’re giving to the animals. And the hormones. Of course we’re gonna get sick. Of course. It’s infuriating, it really is. But you pay more, a little bit, for the great meat, you know, versus paying several years down the line severe medical bills. I’m not saying you couldn’t, one day, have cancer. But you’ve done everything in your power to not get it and I just got the short end of the stick, but at least I can be in control of, at least I’m eating this. Holds me accountable.\nI: Last question, what’s it been like?\nB: I have a really tough stomach. Yeah we, my sisters and I, do talk about it. Definitely check in and, our poor dad. We’re all so females that, sometimes, there’s a point we’re at dinner conversations and we talk about our bowel habits and what was going on. My poor dad. So, yeah, there’s definitely an open communication and you gotta have a sense of humor. You got these issues, you have to have a sense of humor.\nI: What would say to someone that provides comfort? It’s OK, this is life?\nB:\xa0 Um, we just, we just joke. “Hey, remember that one time when,” you know? You just have, you just kind of have a sense of humor about it, accepting what it is and try to stay positive is how we try to move forward. And be on top of it. And really choosing to have a say in relation to our digestion and stuff. Being aware. It’s different for everyone. Be in tune with what your symptoms are. You’re your best advocate.',

At the first step, each conversation/file is presented to GPT and we ask for an answer to the RQ, and the key quotes that support that answer.

In [5]:
# Beware that this cell may show as complete before we've actually got back all the results from GPT
outdir = f"{PROJECT_DIR}/outputs/{session_id}"

output_paths, rq_dict = run_batch_check_for_all_rqs(
            rq_text=rq_text,
            conversation_text_dict = conversation_text_dict,
            output_dir=outdir,
        )

2025-06-18 15:41:51,850 - root - INFO - Using Azure OpenAI
2025-06-18 15:41:51,862 - langfuse - WARNING - Langfuse client is disabled since no public_key was provided as a parameter or environment variable 'LANGFUSE_PUBLIC_KEY'. See our docs: https://langfuse.com/docs/sdk/python/low-level-sdk#initialize-client
2025-06-18 15:41:51,874 - root - INFO - Using Azure OpenAI
2025-06-18 15:41:51,885 - langfuse - WARNING - Langfuse client is disabled since no public_key was provided as a parameter or environment variable 'LANGFUSE_PUBLIC_KEY'. See our docs: https://langfuse.com/docs/sdk/python/low-level-sdk#initialize-client

2025-06-18 15:41:51,899 - root - INFO - Processing batch 1/1
2025-06-18 15:41:51,901 - root - INFO - Processing batch 1/1

The next function just makes the results into a nice tabular format:

In [6]:
# If this cell errors, check that the `mock_session_data/` dir does indeed contain an output file for each RQ
batch_check_all_rqs = create_batch_check_outputs_all_rqs(conversation_text_dict, outdir, rq_dict)
batch_check_all_rqs

Quote NOT found in conversation text:
I’m not really sure. I don’t, I don’t know if they’re taught that in med school that, you know, that it’s not black and white.
Quote NOT found in conversation text:
it gives it a negative connotation, so I was never told celiac.
Accuracy of quotes found in original text: 85.71%
14
12
Quote NOT found in conversation text:
After four or five bites, I can’t eat anymore, feel nauseous.
Quote NOT found in conversation text:
It was really hard. With all the hormones and changing, It just kinda, I think, throws a lot of things off.
Quote NOT found in conversation text:
They wanted to send my sister to the psych unit. They thought it was a mental thing and we’re like, “No, she’s filling up the cup.”
Quote NOT found in conversation text:
It’s a disease on the inside that doesn’t always manifest on the outside.
Quote NOT found in conversation text:
I don’t like the fact I have to take this medication.
Quote NOT found in conversation text:
It’s so hard with these diseases to find it.
Quote NOT found in conversation text:
I would wake up in the morning, take a shit, ah fuck, go back to bed. I’d get up. I’m like, my God, I’ve gotta eat. I, get this, this was going on for weeks.
Quote NOT found in conversation text:
I can live my life and I’m just thinking, and I don’t like to chastise my friends ’cause that’s their choice how they want to raise their family and live. ’Cause, I don’t want to do to him what they’d do to me basically.
Quote NOT found in conversation text:
It’s almost easier to say, “I’m an alcoholic” than “I’m gluten-free.” It’s all easier to say, “I’m an alcoholic” than say “I can’t drink alcohol because I choose to not drink alcohol with you.”
Accuracy of quotes found in original text: 35.71%
14
5

,rq,id,answer,text,timestamp,model,temperature
0,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...","Bowel disorders, it is what it is.",2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
1,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...",I just don’t like the fact I have to take this...,2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
2,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...","I think that’s what happened to me because of,...",2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
3,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...",I found that really hard for doctors. If it’s ...,2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
4,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...",They’re terrified.,2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
5,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...","I could get the flu really, really bad. And th...",2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
6,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...",I’m doing everything that I can in my power as...,2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
7,How do participants feel about their diagnoses?,barbara.vtt,"Participants express a mix of frustration, acc...",You are your best advocate for yourself. Not t...,2025-06-18 14:41:51.901732+00:00,gpt-4o-mini,0
8,How do participants feel about their diagnoses?,sam.vtt,Participants express a complex relationship wi...,"once you put a label on it, you give it power.",2025-06-18 14:41:51.908500+00:00,gpt-4o-mini,0
9,How do participants feel about their diagnoses?,sam.vtt,Participants express a complex relationship wi...,I don’t like to use that label.,2025-06-18 14:41:51.908500+00:00,gpt-4o-mini,0
10,How do participants feel about their diagnoses?,sam.vtt,Participants express a complex relationship wi...,"I think it was the first stages. Um, at least ...",2025-06-18 14:41:51.908500+00:00,gpt-4o-mini,0
11,How do participants feel about their diagnoses?,sam.vtt,Participants express a complex relationship wi...,I had to learn that that’s not my issue. Just ...,2025-06-18 14:41:51.908500+00:00,gpt-4o-mini,0
12,What are some difficulties participants have f...,barbara.vtt,Participants have faced several difficulties d...,"I get, I’ll get joint pains, exhaustion, um, a...",2025-06-18 14:41:51.909082+00:00,gpt-4o-mini,0
13,What are some difficulties participants have f...,barbara.vtt,Participants have faced several difficulties d...,"I had, um, pretty bad hormonal acne, is what t...",2025-06-18 14:41:51.909082+00:00,gpt-4o-mini,0
14,What are some difficulties participants have f...,barbara.vtt,Participants have faced several difficulties d...,"I remember the teachers would not, being, not ...",2025-06-18 14:41:51.909082+00:00,gpt-4o-mini,0
15,What are some difficulties participants have f...,sam.vtt,Participants have faced several difficulties d...,I’d just be exhausted. I’d have to take a nap....,2025-06-18 14:41:51.909578+00:00,gpt-4o-mini,0
16,What are some difficulties participants have f...,sam.vtt,Participants have faced several difficulties d...,"I haven’t lost friends, but I don’t hang out w...",2025-06-18 14:41:51.909578+00:00,gpt-4o-mini,0

At the next step, the answers given per file and per RQ are summarised into a single answer per RQ, and from the quotes that were returned by `run_batch_check_for_all_rqs()`, the best/most illustrative ones are selected for each RQ.

In [7]:
summarize_and_quote_output = generate_summaries_and_quotes(rq_dict, batch_check_all_rqs)
summarize_and_quote_output

{'rq_1_20250618_154151': {'answer': 'Participants have a multifaceted perspective on their diagnoses, characterized by a blend of frustration, acceptance, and a sense of control. They often feel overwhelmed by the medical process and the stigma associated with their conditions, leading to hesitance in fully accepting diagnostic labels. However, they find comfort and empowerment in managing their health through lifestyle choices, such as diet and self-advocacy, which they view as integral to their emotional well-being. This complex relationship highlights both the challenges and the agency participants feel regarding their health.',
  'quotes': ['I just don’t like the fact I have to take this medication.',
   'They’re terrified.',
   'You are your best advocate for yourself. Not taking the medical. Being in tune. It’s clear if I’ve had a bad week. I eat foods I shouldn’t have been eating. I feel really lethargic and exhausted. If you don’t want to feel like this, don’t eat it. It’s pretty immediate.',
   'once you put a label on it, you give it power.',
   'I had to learn that that’s not my issue. Just because you want to drag me into your hell doesn’t mean that, and I had to learn that, how to be strong enough, to stand up for my own health, really.']},
 'rq_2_20250618_154151': {'answer': 'Participants have faced various difficulties due to their conditions, including physical symptoms such as joint pain, exhaustion, and nausea after eating. They encounter challenges in obtaining accurate medical diagnoses and treatment. Socially, they experience feelings of ostracism and misunderstanding related to their dietary restrictions and health issues. Additionally, emotional distress, anxiety, and social isolation are prevalent, often exacerbated by a lack of understanding from others about their conditions.',
  'quotes': ['I get, I’ll get joint pains, exhaustion, um, and I just feel incredibly full.',
   'I had, um, pretty bad hormonal acne, is what they would call it.',
   'I’d just be exhausted. I’d have to take a nap. I mean, literally, take a nap.',
   'I haven’t lost friends, but I don’t hang out with them as much as I used to. I mean, not nearly as much. I was out every night. Now, it’s sometimes once a month.',
   'I remember the teachers would not, being, not really getting it.']}}

The final thing is to turn this output into a table format that can be converted to excel. The excel output also needs to contain conversation/file IDs for each quotes, so we check for exact matches between the quotes returned by `generate_summaries_and_quotes()` and the original text of each conversation/file.

In [8]:
summarise_output_df = create_final_output_df(rq_dict, conversation_text_dict, summarize_and_quote_output)

summarise_output_df.reset_index().to_csv(os.path.join(outdir, "summarise_output_df.csv"), index=False)

create_output_excel(summarise_output_df, outdir)

RQ ID: rq_1_20250618_154151
QUOTE:
I just don’t like the fact I have to take this medication.
→ FOUND IN: barbara.vtt

QUOTE:
They’re terrified.
→ FOUND IN: barbara.vtt

QUOTE:
You are your best advocate for yourself. Not taking the medical. Being in tune. It’s clear if I’ve had a bad week. I eat foods I shouldn’t have been eating. I feel really lethargic and exhausted. If you don’t want to feel like this, don’t eat it. It’s pretty immediate.
→ FOUND IN: barbara.vtt

QUOTE:
once you put a label on it, you give it power.
→ FOUND IN: sam.vtt

QUOTE:
I had to learn that that’s not my issue. Just because you want to drag me into your hell doesn’t mean that, and I had to learn that, how to be strong enough, to stand up for my own health, really.
→ FOUND IN: sam.vtt

RQ ID: rq_2_20250618_154151
QUOTE:
I get, I’ll get joint pains, exhaustion, um, and I just feel incredibly full.
→ FOUND IN: barbara.vtt

QUOTE:
I had, um, pretty bad hormonal acne, is what they would call it.
→ FOUND IN: barbara.vtt

QUOTE:
I’d just be exhausted. I’d have to take a nap. I mean, literally, take a nap.
→ FOUND IN: sam.vtt

QUOTE:
I haven’t lost friends, but I don’t hang out with them as much as I used to. I mean, not nearly as much. I was out every night. Now, it’s sometimes once a month.
→ FOUND IN: sam.vtt

QUOTE:
I remember the teachers would not, being, not really getting it.
→ FOUND IN: barbara.vtt

This is what the tabular output looks like:

In [9]:
summarise_output_df

,question,answer,quote,source
0,How do participants feel about their diagnoses?,Participants have a multifaceted perspective o...,I just don’t like the fact I have to take this...,barbara.vtt
1,How do participants feel about their diagnoses?,Participants have a multifaceted perspective o...,They’re terrified.,barbara.vtt
2,How do participants feel about their diagnoses?,Participants have a multifaceted perspective o...,You are your best advocate for yourself. Not t...,barbara.vtt
3,How do participants feel about their diagnoses?,Participants have a multifaceted perspective o...,"once you put a label on it, you give it power.",sam.vtt
4,How do participants feel about their diagnoses?,Participants have a multifaceted perspective o...,I had to learn that that’s not my issue. Just ...,sam.vtt
5,What are some difficulties participants have f...,Participants have faced various difficulties d...,"I get, I’ll get joint pains, exhaustion, um, a...",barbara.vtt
6,What are some difficulties participants have f...,Participants have faced various difficulties d...,"I had, um, pretty bad hormonal acne, is what t...",barbara.vtt
7,What are some difficulties participants have f...,Participants have faced various difficulties d...,I’d just be exhausted. I’d have to take a nap....,sam.vtt
8,What are some difficulties participants have f...,Participants have faced various difficulties d...,"I haven’t lost friends, but I don’t hang out w...",sam.vtt
9,What are some difficulties participants have f...,Participants have faced various difficulties d...,"I remember the teachers would not, being, not ...",barbara.vtt